services:

  # ===============================
  # Backend APP Server (port 8080)
  # ===============================
  backend:
    build:
      context: ./backend       # folder chứa Dockerfile của app server
      dockerfile: Dockerfile
    container_name: bookstore-backend
    ports:
      - "8080:8080"
    networks:
      - bookstore_net

  # ===============================
  # BFF Server (Auth0 callback)
  # ===============================
  bff:
    build:
      context: ./bff       # folder chứa Dockerfile của bff server
      dockerfile: Dockerfile
    container_name: bookstore-bff
    ports:
      - "8081:8081"
    networks:
      - bookstore_net

  # ===============================
  # Static Frontend Server (Nginx)
  # ===============================
  frontend:
    build:
      context: ./frontend      # folder chứa Dockerfile của static server
      dockerfile: Dockerfile
    container_name: bookstore-frontend
    ports:
      - "8088:8088"
    networks:
      - bookstore_net
    depends_on:
      - backend
      - bff

  # ===============================
  # Redis Service (Cache & Session)
  # ===============================
  redis:
    image: redis:7.0-alpine
    container_name: bookstore_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - bookstore_net

volumes:
  redis_data:

networks:
  bookstore_net:
    driver: bridge
